{
 "title": "Envoy - HTTP Response Stats",
 "time": { "from": "2022-03-03T09:13:39.464Z", "to": "2022-03-03T09:22:34.565Z" },
 "templating": {
  "list": [
   { "name": "interval", "query": "5s,10s,30s,1m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "HTTP response distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_http\"}",
     "legendFormat": "{{envoy_response_code_class}}00"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\"}[$interval])) / sum(rate(envoy_cluster_upstream_rq_xx[$interval]))",
     "legendFormat": "failure rate"
    }
   ]
  },
  {
   "title": "Cluster Health Alert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "envoy_cluster_health_check_healthy{envoy_cluster_name=\"application\"} / max_over_time(envoy_cluster_membership_total{envoy_cluster_name=\"application\"}[1d])",
     "legendFormat": "healthy ratio"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 } },
  { "title": "Alert History", "type": "alertlist", "gridPos": { "h": 8, "w": 6, "x": 5, "y": 8 } },
  {
   "title": "Outlier Detection - Active Ejections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "envoy_cluster_outlier_detection_ejections_active{envoy_cluster_name=\"application\"} / max_over_time(envoy_cluster_membership_total{envoy_cluster_name=\"application\"}[1d])"
    }
   ]
  },
  {
   "title": "Failure Rate Alert",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_xx[1m]))"
    }
   ]
  },
  {
   "title": "HTTP response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"application\"}[$interval]))"
    }
   ]
  }
 ]
}