{
 "title": "Traefik - HTTP Response Stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "HTTP response distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "traefik_entrypoint_requests_total{entrypoint=\"http\"}",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=~\"5..\"}[$interval])) / sum(rate(traefik_entrypoint_requests_total[$interval]))",
     "legendFormat": "failure rate"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 } },
  { "title": "Alert History", "type": "alertlist", "gridPos": { "h": 8, "w": 6, "x": 5, "y": 8 } },
  {
   "title": "Failure Rate Alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=~\"5..\"}[1m])) / sum(rate(traefik_entrypoint_requests_total[1m]))"
    }
   ]
  }
 ]
}