{
 "title": "Envoy - HTTP Response Stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "5s,10s,30s,1m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "HTTP response distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_http\"}",
     "legendFormat": "{{envoy_response_code_class}}"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\"}[$interval])) / sum(rate(envoy_cluster_upstream_rq_xx[$interval]))",
     "legendFormat": "failure rate"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 } },
  { "title": "Alert History", "type": "alertlist", "gridPos": { "h": 8, "w": 6, "x": 5, "y": 8 } },
  {
   "title": "Cluster Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_health_check_healthy{envoy_cluster_name=\"application\"} / max_over_time(envoy_cluster_health_check_healthy{envoy_cluster_name=\"application\"}[1d])",
     "legendFormat": "healthy ratio"
    }
   ]
  },
  {
   "title": "Failure Rate Alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_xx[1m]))"
    }
   ]
  }
 ]
}