version: '3'

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.6.1
    ports:
      # The HTTP port
      - "80:80"
      # The TCP port
      - "44:44"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/routes.toml:/etc/traefik/routes.toml:ro
  envoy:
    # The official v2 Traefik docker image
    image: envoyproxy/envoy:v1.20.2
    ports:
      # The HTTP port
      - "10000:10000"
      # The Admin UI
      - "9901:9901"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
  application-1:
    image: quarkus/application-jvm:1.0
    ports:
      - "8090:8080"
    labels:
      killable: true
  application-2:
    image: quarkus/application-jvm:1.0
    ports:
      - "8091:8080"
    labels:
      killable: true
  mongo:
    image: mongo:5.0.6
    ports:
      - "27017:27017"
    labels:
      killable: true
  prometheus:
    image: prom/prometheus:v2.33.4
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:8.3.7
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - 3000:3000

volumes:
  prometheus-data:

